seed: 436
exp_name: ex4
env_name: CartPole-v1
agent_name: dqn
run_id: ??? # decided during execution

n_actions: 2
state_shape: [4,]

train_episodes: 4000
max_episode_steps: 200
test_episodes: 10
random_episodes: 10
glie_b: 200
gamma: 0.99 # discount term in Q learning
batch_size: 256
buffer_size: 50000

testing: false
save_video: false
save_logging: true
save_model: true
silent: false # print restuls to the terminal if false
use_wandb: true

run_suffix: 0

grad_clip_norm: 1
hidden_dims: [16, 16]
tau: 0.001
lr: 5e-5