seed: null
exp_name: ex5
env_name: InvertedPendulum-v4
run_id: ??? # decided during execution

train_episodes: 1000
gamma: 0.99
lr: 2e-3

testing: false
model_path: default

save_video: false
save_logging: true
save_model: true
silent: false

run_suffix: 0
seed: 409